### ISSUE TITLE
Time Based on UTC Offset

### ISSUE THREAD

**Issue by webluke** [White-Tiger/T-Clock#154] opened 2018-06-25 19:13 UTC
This seems like something that should have been in already but using an hour setting based on UTC offset. An example would be in the US we are on Mountain Daylight Time, but switch to Mountain Standard Time in winter, so then my offset for UTC goes from -06 to -07. If I am using system time offset with the W+6, at time change the times I have set with offsets are wrong. But if you based it off UTC if your local time could changes and the clocks based on UTC would stay correct to the UTC offset settings. 

If you add a **U** for 24 hour, **u** for 12 hour, then **+-** the **UTC offset number** to base the time on UTC offset.

Ex: _U+0_ would be UTC, _U-7_ would be Mountain Time, both in 24 hour. and  _u+2_ would be South Africa Standard Time 12 hour.

It just seems intuitive to set the hour based on UTC offsets rather than local time offset. There is some other open issues that mention UTC but I think this enhancement would help them with the same thing they want to do, but this is a new way of displaying the time based on UTC so it dose not duplicate any of those ideas and would not break old configurations with a new option value to look for when parsing the time format settings.

Thanks for maintaining a useful program :)

**Comment by White-Tiger** [comment] 2018-06-26 07:34
closed as duplicate of #32 _(since you've searched already, yes it's an indirect duplicate, but part of what I planned to do and UTC goes hand-in-hand with that)_

Reason why I haven't implemented UTC when I first got that idea, is that I also want to rewrite the way formats are handled internally. How I implement that effects existing and planned formats _(one reason for the rewrite)_, so I rather not add new ones before the "infrastructure" is set.

**P.S.** I prefer `UTC±x` as that's what's normally used if one mentions an offset. `U±x` isn't intuitive.
Yet it's not as easy as adding a simple ±, there's daylight savings that need (or don't need) to be handled, there are countries with 30 minute offsets so that also affects how it needs to be implemented.

**Closed as completed by White-Tiger** 2018-06-26 07:34 UTC
