### ISSUE TITLE
Show desktop button sometimes disappears

### ISSUE THREAD

**Issue by TClockBroughtMeHere** [White-Tiger/T-Clock#99] opened 2017-05-21 20:23 UTC
Hi! I'm writing this bug report just that you know, because I don't have very much information for you. My problem is that the "show desktop" button in the taskbar sometimes disappears. It came back when I logged in. I'm using Windows 10 version 1607.

**Comment by wokawoka** [comment] 2017-05-27 03:08
I'm experiencing the exact same problem. It happens about once every two days here. I couldn't notice a pattern or a trigger but i suspect that is linked with the lenght of the date/time shown  t-clock that in some days of the week+moment of the day blocks the desktop button on the bottom righ edge of the screen.
If it can help the clock format that I'm using is "ddd dd/mm - HH:nn" with position -5 in width and -2 horizontal, and the font is Segoe UI bold with size 8.

**Comment by jeytee84** [comment] 2017-12-18 10:40
Same here
https://imgur.com/a/aTpOk

**Comment by White-Tiger** [comment] 2018-01-23 14:36
quite sure it's a duplicate of #87 
should be fixed in upcoming version.

**Closed by White-Tiger** 2018-01-23 14:36 UTC
