### ISSUE TITLE
Clock text in 2.4.1 (beta) loses color

### ISSUE THREAD

**Issue by lengoldstein** [White-Tiger/T-Clock#46] opened 2016-08-04 18:21 UTC
The Windows 10 Anniversary Update wiped out my previous version of TClock, which worked fine under the original Win10, but I've just installed TClock's beta update and now it's running again.  Thank you, White-Tiger and Stoic Joker, and sure, Kazubon and Two_toNe too, why not?

I find that I can change the clock text to any color I want, but after I exit from the Options menu, when I hover the mouse over the text it immediately switches back to the default, white.  Not a critical problem, it just means I have to avoid that corner of the screen or reselect the color anytime I go there, but it would be nice to have the color stay put.

**Comment by White-Tiger** [comment] 2016-08-04 23:09
duplicate of #43

**Closed by White-Tiger** 2016-08-04 23:09 UTC
Labels: duplicate
