### ISSUE TITLE
Display Multiple Clocks for Multiple Timezones

### ISSUE THREAD

**Issue by nathanila** [White-Tiger/T-Clock#71] opened 2016-10-15 15:28 UTC
I would like to display multiple clocks for multiple timezones.  For example, I would like to show India, UTC, London, Eastern, Central, Mountain, Pacific and local timezones.  All of these would display on the taskbar in that order from left to right.  Each one I would like to customize the format string.

**Comment by nathanila** [comment] 2016-10-18 20:23
I was using Anuko World Clock which has this requested feature and my trial period ended.  I am anxious to know when this enhancement will be worked on.  Is it next in your queue?  Or are you thinking about pushing it for much later?

**Comment by White-Tiger** [comment] 2016-10-18 21:18
It's one of those things I've imagined to implement one day, in fact it's part of an internal format and drawing refactoring... so it's on my "to-do" since I've started to maintain T-Clock (well 3 months after that)

It won't be coming anytime soon though :(

**Comment by gaudibr** [comment] 2017-05-30 14:40
I second the request. There aren't many great multi-timezone clocks out there for Windows and most of them lack the calendar feature. T-Clock is the best calendar viewing software for windows, but it removes the system default possibility of seeing 3 clocks... would be great to have them both. Since Nathanila has requested this over 6 months ago, I thought I'd bump this request up if possible.

**Comment by White-Tiger** [comment] 2018-03-07 09:13
Closed as duplicate of #32

**Closed by White-Tiger** 2018-03-07 09:13 UTC
Labels: enhancement

**Comment by nathanila** [comment] 2018-03-07 14:57
This is not a duplicate of #32 or #141.

**Comment by White-Tiger** [comment] 2018-03-08 07:05
why not?
#32 is pretty much about being able to use something like:

**Comment by White-Tiger** [comment] 2018-03-08 07:08
why not?
#32 is pretty much about being able to use something like:
```
"London" UTC+1 h:nn:ss tt\nddd, mm/dd/yy\n
"US East" UTC-5 h:nn:ss tt\nddd, mm/dd/yy\n
"Steam's time" UTC-8 h:nn:ss tt\nddd, mm/dd/yy\n
```

Isn't this what this issue is also about?

**Comment by nathanila** [comment] 2018-03-08 14:50
Simply writing UTC-5 is not going to handle daylight savings time for US east coast.  You would have to allow for writing ET or Eastern or whatever timezone.

The \n will make the display vertical.  What if the user wants to put the location above the time for each location and then put the locations horizontal.

I suppose if you can figure out the layout issues with the format string, then yes this issue is a duplicate.

**Comment by White-Tiger** [comment] 2018-03-08 15:20
it's been a quick example. I can basically guarantee it won't look like that once implemented.
Also, using new line or what ever is obviously up to the user. Daylight savings are also already accounted for if you take a look at #75 
Currently I would imagine something like `UTC±x[:y]` to select the timezone + a modifier to use daylight savings or maybe even to use a modifier to NOT use daylight savings since I guess it's more common to use them.
For example, the real timezone for British people is `UTC+0/GMT+0`, French and other Europeans got `UTC+1` and the US' PST is `UTC-8`. For these, `UTC+1`, `UTC+2` and `UTC-7` are all their daylight saving times which is something that's either active or not, but never their actual timezone. _(if at all, only during the summer... yet it's an "addon" on their "real" timezone)_

**Comment by gaveitatry02** [comment] 2020-01-08 20:32
Any news about this?  I've seen threads about it dating back as far as 2016 (four years ago) and this latest post by White-Tiger was 1 year and 10 months ago (almost two years).
