### ISSUE TITLE
time update not occurring unless t-clock gains or loses focus

### ISSUE THREAD

**Issue by rodolbud** [White-Tiger/T-Clock#1] opened 2015-03-18 16:01 UTC
I am using 64-bit 2.3.2 build 151. I am experiencing an issue where the time is not updating unless t-clock gains or loses focus in the system tray.  I am using "Custom Format" on "Time Format" tab as "dddd\nmm/dd/yyyy\nhh:nn:ss".

**Comment by White-Tiger** [comment] 2015-03-18 19:45
is your format related to this problem? Or does it also occur when you disable the "Custom Format" checkbox (don't worry, you will not loose your custom format unless you change the locale^^ But that's a bug)

**Comment by rodolbud** [comment] 2015-03-18 19:54
i tried unchecking the "Custom Format" (btw - I did lose my custom format, but anyway). Unchecking the Custom Format did not help the problem - it still exists.
OS = Windows 7 (Enterprise) 64-bit with Service Pack 1.

**Comment by White-Tiger** [comment] 2015-03-18 20:00
by "won't loose" I've meant that T-Clock will remember your custom format and you can safely enable it again... at least should be...
Anyway, does this problem exist from the very beginning, or did it happen after some time?
Was there any T-Clock version that you know that worked?

**Comment by rodolbud** [comment] 2015-03-18 20:11
RE: "Won't lose" - you are correct, when I re-enabled it, it re-remembered by format.

This is the only White Tiger version that I have installed.  I have not had it for very long, so likely (although I cannot confirm), it has done it since installation.  I had previously installed a Stoic Joker version (32-bit running on Windows 7 32-bit), but this problem did not occur with that version. I forget the version number of the Stoic Joker version, and my computer has since been "wiped" and re-imaged with 64-bit Win7.

**Comment by White-Tiger** [comment] 2015-03-18 20:18
well... will try to reproduce it the following days, using a virtual Win7 machine.

**Comment by White-Tiger** [comment] 2015-04-08 13:21
might take a few more weeks, don't have enough disk space to setup a VM right now...

**Comment by White-Tiger** [comment] 2015-04-11 18:45
well.. just tested on a Win7 Ultimate and everything seems to work as it should... so clock refreshes, etc.

so right now, I can't reproduce it... Could you maybe boot your Windows into safe mode and run T-Clock there?
Right now I have literally no clue :P I could understand if the clock display freezes after some time, or a stand-by / hibernate, but not really from the very beginning and then working on mouse over, etc.

**Comment by White-Tiger** [comment] 2015-04-13 19:20
Any special settings that differ from vanilla Windows?
So, any classic themes, XP style, custom themes? Anything that might mess with the window system?

**Comment by biltong11** [comment] 2015-07-30 08:32
I also experience this issue with the clock not updating - but not all the time. If I reboot, the problem clears and the clock works fine. I cannot identify at what point it stops working, but usually after a few days and the PC hasn't been rebooted.
Win 7 Pro, 64 bit. No themes or other Windows mods.

**Comment by White-Tiger** [comment] 2015-07-30 08:42
PC always running 24/7 or does it go to sleep/hibernate from time to time?

**Comment by hspindel** [comment] 2015-07-30 09:56
I also experience time update not occurring.  Computer runs 24/7, never 
sleeps/hibernates.

**Comment by White-Tiger** [comment] 2015-07-30 21:00
I guess simply exiting T-Clock and starting it again also temporarily "fixes" this issue? @biltong11 said you'll reboot to "fix" it...

**Comment by biltong11** [comment] 2015-07-30 21:52
To be honest I am not sure whether closing and opening T-Clock will fix it. Rather silly, but I don't think I have tried that. I haven't had the issue this week so far, but will  certainly try it when it happens again.

To answer the previous question - no sleep or hibernation.

**Comment by hspindel** [comment] 2015-07-31 01:25
Closing and reopening fixes it for me.

**Comment by biltong11** [comment] 2015-08-05 13:40
I have had the issue occur again, and I can confirm closing and reopening does indeed fix the problem.

**Comment by White-Tiger** [comment] 2015-10-19 19:07
can you guys test my [latest pre-release](https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.0%23351-rc) ?
Not sure if it is fixed, if now: try to *rightclick->"Refresh T-Clock"* and report back if that causes it to refresh again..

**Comment by biltong11** [comment] 2015-11-20 15:50
So far so good! Since updating I have not had the problem again, but I will continue monitoring.

(One thing I have noticed with the new version - the calendar opens up in the centre bottom of the screen, whereas before it would always open bottom right above the clock. I cannot fin any option to change this behaviour. Is this by design? If not, do I open a new issue?)

Thank you for your efforts with this fantastic software!

**Comment by White-Tiger** [comment] 2015-11-20 18:10
It's a regression... if you had a 32bit OS, you wouldn't even notice xD
But it likewise also kills the multi-monitor support the same way.. *(that is, Windows' inbuild calendar should be centered on non-primary monitors..)*

I've actually seen this "issue" before you and another reported it.. hope you can live with this in the mean time... I might push a new version next week if that's ok with you

Probably also enough time for this issue here to "verify" :P

**Comment by White-Tiger** [comment] 2016-08-03 20:15
closing for now, reopen when it happens again.

**Closed by White-Tiger** 2016-08-03 20:15 UTC
Labels: bug
