### ISSUE TITLE
Tooltip text to show multiple timezones

### ISSUE THREAD

**Issue by syper** [White-Tiger/T-Clock#81] opened 2016-12-22 11:31 UTC
Currently I have the mouse tooltip text showing the default ""T-Clock"\nLDATE"

Is it possible to show multiple timezones, something that would show the output like:

"
Current location: 10:40
South Korea: 19:40
"

**Comment by White-Tiger** [comment] 2016-12-22 12:22
currently only though the usual `W±x` format as long as hours are enough... _(no ± 30 minutes, no date / weekday)_

**Comment by syper** [comment] 2016-12-22 22:23
Great tip White-Tiger, I did not know that it was possible to use W±x

The command '  LDATE \n "Norway:" W+0:n \n "South Korea:" W+8:n\n  ' is now showing the correct time but the code will not adapt to timezone changes.  Traveling to South Korea, Windows will update the time automatically, but this code will need to be adjusted manually (I guess I will try to make a 1 click registry or a batch file, nevertheless, will require clicking on every travel!)

Maybe finding a way for T-Clock to do this calculation could be something you would consider tackling!! :)

**Comment by White-Tiger** [comment] 2016-12-23 13:29
it's on the ToDo for a long time... some sort of `UTC+x` format that changes all following formats...
The `w±x` is quite a weird format indeed... don't see much use in a relative format...

**Comment by cyptus** [comment] 2017-03-15 14:57
you could turn off automatic time in windows settings, so the time will not change if you travel into another time zone. sure you will need to view the tooltip for the current time in your current timezone. to change this you could create a batch file which changes the settings which is the "primary clock" (as you mentioned above) and add the script as an quick menu file on the context menu of t-clock.

**Comment by White-Tiger** [comment] 2018-01-28 21:00
Suggestion has also been posted on the forums: http://donationcoder.com/forum/index.php?topic=43752.0

**Comment by White-Tiger** [comment] 2018-03-07 09:16
Closed as duplicate of #32

**Closed by White-Tiger** 2018-03-07 09:16 UTC

**Comment by ghost** [comment] 2023-07-27 08:13
> currently only through the usual `W±x` format as long as hours are enough... _(no ± 30 minutes, no date / weekday)_

@White-Tiger , can you help me here? Is +30 mins is available now? If yes, how to set it up?
