### ISSUE TITLE
Feature Request: Separate Calendar's Month Background and Day colors

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [White-Tiger/T-Clock#90] opened 2017-03-11 05:49 UTC
First, thanks a lot for creating this :D

At the moment, the "month background" color is used for both the month header, but also the color of the days. I want to ask if you could seperate them into 2 different options so their color is configurable separately - as the day headers are more of a foreground instead of a background color.
 
In my case, I have my calendar configured with a darkish gray and would like the month header to be a tad darker. But then the days blend into the background to much. And there are a lot of other combinations where the effect would not be feasable, I think.

TIA :)

**Comment by White-Tiger** [comment] 2017-03-11 08:53
duplicate of #61

**Closed by White-Tiger** 2017-03-11 08:53 UTC
Labels: duplicate
