### ISSUE TITLE
Proposal of program improvements - Multilanguage interface and installer

### ISSUE THREAD

**Issue by bovirus** [White-Tiger/T-Clock#115] opened 2017-09-08 08:25 UTC
@White-Tiger 

Thanks a lot for your interesting software.

Do you have a plan to make the software multi-language?
I believe that it's an important step up for many users.

Another steps could the creation of an installer.

Thanks.

**Comment by White-Tiger** [comment] 2017-09-08 12:27
Your second "request" is a duplicate of #23 
Your first pretty much of #42 , though I do/did consider it, but it's obviously very-low priority... That said, I might at some time provide the mechanism, but won't do any translations myself _(or "update" them)_

**Closed by White-Tiger** 2017-09-08 12:27 UTC

**Comment by bovirus** [comment] 2017-09-08 12:53
Thanks for info about the installer.
I will contribute with Italian language (if it needs).

I proposed to enable program ad multi-language GUI because one time that you can enable it I will help you creating the Italian language.

Thanks.
