### ISSUE TITLE
Windows 10 Anniversary Update Issue

### ISSUE THREAD

**Issue by blueWeber** [White-Tiger/T-Clock#41] opened 2016-07-28 19:58 UTC
issue #1: show below image
http://blueweber.cafe24.com/temp/tcbug.jpg

issue #2: when mouse left click, don't appear windows calendar

**Comment by acethical** [comment] 2016-07-29 17:17
Same.
Insider, release preview channel, updated from 10586 to 14393.5.

**Comment by White-Tiger** [comment] 2016-07-29 18:57
duplicate of #39

**Closed by White-Tiger** 2016-07-29 18:57 UTC
Labels: duplicate

**Comment by White-Tiger** [comment] 2016-08-03 20:13
Alpha/Beta *(something probably unstable)* release here: https://github.com/White-Tiger/T-Clock/releases
