### ISSUE TITLE
numeric day of week

### ISSUE THREAD

**Issue by sfranks916** [White-Tiger/T-Clock#109] opened 2017-08-16 23:07 UTC
We have work week with the Wu (and similar) format string.  Allowing "ww33 Wed" using "wwWu ddd".  I would like to request an enhancement to add the numeric day of week to create "ww33.3".

Love this clock over all.  Thank you.

**Comment by White-Tiger** [comment] 2018-01-24 11:17
this was a duplicate of #53 and thereby already fixed

**Closed by White-Tiger** 2018-01-24 11:17 UTC
Labels: duplicate
