### ISSUE TITLE
v2.4.2 (0xc000007b)

### ISSUE THREAD

**Issue by Diedrichs** [White-Tiger/T-Clock#66] opened 2016-09-24 10:31 UTC
I get the following message (windows 10):
The application failed to start correctly (0xc000007b)
with v.2.4.1 it is ok!

Direcx,  chdsk, sfc /scannow it is all ok!

Sorry my bad English!
![24-09-_2016_12-10-31](https://cloud.githubusercontent.com/assets/5257366/18807852/c129a940-8252-11e6-90c2-69907eeae7af.jpg)

**Comment by White-Tiger** [comment] 2016-09-24 13:32
duplicate of #58

Since this problem only occurs with the non-static build, it's only likely to be some `Microsoft Visual C++ 2010 Redistributable` issue.. _(see [#requirements](/White-Tiger/T-Clock#requirements))_

It's either not properly installed, or some 3rd party put their own 32bit version into the path _(but that'll mean that `Clock.exe` and `Clock64.exe` output different error messages (or none at all))_

**Closed by White-Tiger** 2016-09-24 13:32 UTC
Labels: duplicate, invalid

**Comment by Diedrichs** [comment] 2016-10-05 00:42
I Have installed Microsoxt Visual C++ 2010 new, but it is the same result

Best regards
Harald

**Comment by Diedrichs** [comment] 2016-10-16 18:19
Have you any idea?

Best regards
Harakd

**Comment by KitMcGuire** [comment] 2016-10-16 18:25
It works fine with Windows 10 x64, but not with Windows 10 x86.
I have tried many options and I can not get rid of the blurring effect right of the box.

Kit McGuire
206 N. Titel St.
Payson, AZ 85541
USA
(+1) 928-978-3795
https://www.google.com/maps/place/206+N+Titel+St,+Payson,+AZ+85541/@34.2433935,-111.3154276,17z/data=!3m1!4b1!4m2!3m1!1s0x872c10c1e9ac8ab1:0x9d725ab491883472
Check me out on Facebook: https://www.facebook.com/KitMcGuire
  ----- Original Message -----

**Comment by White-Tiger** [comment] 2016-10-16 18:45
please stick to issue #58, this one is a duplicate.

**P.S.** this issue also happens on 64bit Win10 for some... yet it never happened to me even with different Win10 versions _(like first official release, Anniversary version, latest version, insider build)_
