### ISSUE TITLE
Improvement for Alternate time zone (w and W) for India: time difference with WE = 4.5 hours

### ISSUE THREAD

**Issue by mrvainv2** [White-Tiger/T-Clock#83] opened 2017-01-05 16:44 UTC
**Issue:** unable to add an alternative time zone for India. India has 4 hours and 30 minutes difference with Western Europe. I was only able to add integers in the configuration for the "advanced clock format"

**Comment by White-Tiger** [comment] 2017-01-05 23:19
because those "offsets" aren't real time zones anyway :P Guess that's why they never supported sub-hours

**Comment by gwired2015** [comment] 2017-01-19 17:43
+1 for the enhancement.

Doesn't windows have a Time Zone Index you could use?  

https://msdn.microsoft.com/en-us/library/ms912391(v=winembedded.11).aspx

**Comment by White-Tiger** [comment] 2017-01-19 20:17
that's not really related... I wouldn't even consider the use of named timezones, simply for that reason that something like `UTC±x` is way more universal _(and probably more known than the name of a timezone)_.
In fact: there's an request ongoing to implement the display of the current timezone but isn't easy to implement due to overlapping timezones and that there isn't any standardized format, which means you can't please everyone,

**Comment by White-Tiger** [comment] 2018-03-07 09:16
Closed as duplicate of #32

**Closed by White-Tiger** 2018-03-07 09:16 UTC
Labels: enhancement
